### ISSUE TITLE
Layer panel stretchable

### ISSUE THREAD

**Issue by davidfuchsa** [Pixofield/keyshape-plugins#3]
Hi. I am using a lot of layers and I am nesting them (screenshot)
![screen shot 2018-08-08 at 13 39 16](https://user-images.githubusercontent.com/25434515/43835001-854b2344-9b10-11e8-9efc-2ed1ad39eead.png)

I would really appreciate option to set width of layer pannel by draging it. Are you planning to add this little UI change?

**Comment by djablo74** [comment]
That would be awesome, yes…

**Comment by Pixofield** [comment]
Keyshape 1.8 has a resizable panel.
