### ISSUE TITLE
JS Editor

### ISSUE THREAD

**Issue by 360fun** [Pixofield/keyshape-plugins#5]
Would be awesome to have a Javascript editor integrated into Keyshape!

My current workflow:
- I export the animation
- I add my JS code
- if I need to modify the animation I've to backup somewhere the JS code
- export again the animation
- open the new one and paste it

When you do this several times you lose time and especially risk to forget to backup the JS and overwrite the code. Just a simple text editor with JS syntax highlighting would be perfect (no parsing needed): the code would be automatically added to <script></script> when exported, saving a lot of time and mental sanity! 😁

This can be (maybe?) a plugin or (better) a new Keyshape feature. 🚀

**Comment by Pixofield** [comment]
Keyshape version 1.12.0 added a dialog to edit JavaScript in SVG documents (no syntax highlighting). It can be accessed in Keyshape by choosing the View > Show Document Scripts... menu command.

**Comment by 360fun** [comment]
Yeah, I noticed and appreciate: thank you! 🚀
